### PR TITLE
Documentation edits

### PR DESCRIPTION
**Pull request by ggazzola**

### CODE REVIEW

**Comment by ggazzola** [comment]
@pzingg, @nhpackard : I made a few text edits to the documentation. Please check and and merge if all OK.

**Comment by nhpackard** [comment]
I am in the middle of more extensive edits.

I have incorporated all of your edits into my version (I'm pretty sure!!)

**Comment by nhpackard** [comment]
Any particular reason you forked the repo instead of just creating a branch?

**Comment by ggazzola** [comment]
No, I did it accidentally.

**Pull request closed without merging**
